[build]
  command = "npm run breadbox && npm run build"
  publish = "public"
  functions = "functions"

[[plugins]]
  package = "netlify-plugin-inline-source"

[[plugins]]
  package = "netlify-plugin-deploy-preview-commenting"
